spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/anything
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  properties:
   hibernate:
  # show_sql: true
    format_sql: true

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug



server:
  port: 8090